export const LOG_COLORS = [
  'black',
  'red',
  'green',
  'yellow',
  'blue',
  'magenta',
  'cyan',
  'white',
  'brightBlack',
  'brightRed',
  'brightGreen',
  'brightYellow',
  'brightBlue',
  'brightMagenta',
  'brightCyan',
  'brightWhite',
  'bgBlack',
  'bgRed',
  'bgGreen',
  'bgYellow',
  'bgBlue',
  'bgMagenta',
  'bgCyan',
  'bgWhite',
  'bgBrightBlack',
  'bgBrightRed',
  'bgBrightGreen',
  'bgBrightYellow',
  'bgBrightBlue',
  'bgBrightMagenta',
  'bgBrightCyan',
  'bgBrightWhite',
  'reset',
  'carriage',
] as const;

export type LogColor = typeof LOG_COLORS[number];

export const useColors = () => {
  const colors: Record<LogColor, string> = {
    black: '\u001b[30m',
    red: '\u001b[31m',
    green: '\u001b[32m',
    yellow: '\u001b[33m',
    blue: '\u001b[34m',
    magenta: '\u001b[35m',
    cyan: '\u001b[36m',
    white: '\u001b[37m',
    brightBlack: '\u001b[90m',
    brightRed: '\u001b[91m',
    brightGreen: '\u001b[92m',
    brightYellow: '\u001b[93m',
    brightBlue: '\u001b[94m',
    brightMagenta: '\u001b[95m',
    brightCyan: '\u001b[96m',
    brightWhite: '\u001b[97m',
    bgBlack: '\u001b[40m',
    bgRed: '\u001b[41m',
    bgGreen: '\u001b[42m',
    bgYellow: '\u001b[43m',
    bgBlue: '\u001b[44m',
    bgMagenta: '\u001b[45m',
    bgCyan: '\u001b[46m',
    bgWhite: '\u001b[47m',
    bgBrightBlack: '\u001b[40m',
    bgBrightRed: '\u001b[41m',
    bgBrightGreen: '\u001b[42m',
    bgBrightYellow: '\u001b[43m',
    bgBrightBlue: '\u001b[44m',
    bgBrightMagenta: '\u001b[45m',
    bgBrightCyan: '\u001b[46m',
    bgBrightWhite: '\u001b[47m',
    reset: '\u001b[0m',
    carriage: '\r',
  };

  return {
    ...colors,
  };
};
